name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Checkout
        uses: actions/checkout@v2
      - run: |
          ./gradlew buildPlatformImage -PghUser=${{secrets.PKG_USER}} -PghPass=${{secrets.PKG_PW}}