name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to docker registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.PKG_USER }}
          password: ${{ secrets.PKG_PW }}
      - run: |
          ./gradlew buildPlatformImage -PghUser=${{ secrets.PKG_USER }} -PghPass=${{ secrets.PKG_PW }}