name: Publish

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Checkout
        uses: actions/checkout@v2
      - shell: bash
        env:
          PKG_USERNAME: ${{ secrets.PKG_USER }}
          PKG_PASSWORD: ${{ secrets.PKG_PASS }}
        run: |
          ./gradlew buildPlatformImage -PghUser="$PKG_USERNAME" -PghPass="$PKG_PASSWORD"